/* Wrapper to compile generated pose model with unique public symbols. */

#define LL_ATON_EC_Network_Init_network LL_ATON_EC_Network_Init_pose
#define LL_ATON_EC_Inference_Init_network LL_ATON_EC_Inference_Init_pose
#define LL_ATON_Set_User_Input_Buffer_network LL_ATON_Set_User_Input_Buffer_pose
#define LL_ATON_Get_User_Input_Buffer_network LL_ATON_Get_User_Input_Buffer_pose
#define LL_ATON_Set_User_Output_Buffer_network LL_ATON_Set_User_Output_Buffer_pose
#define LL_ATON_Get_User_Output_Buffer_network LL_ATON_Get_User_Output_Buffer_pose
#define LL_ATON_EpochBlockItems_network LL_ATON_EpochBlockItems_pose
#define LL_ATON_Output_Buffers_Info_network LL_ATON_Output_Buffers_Info_pose
#define LL_ATON_Input_Buffers_Info_network LL_ATON_Input_Buffers_Info_pose
#define LL_ATON_WeightEncryption_Info_network LL_ATON_WeightEncryption_Info_pose
#define LL_ATON_BlobEncryption_Info_network LL_ATON_BlobEncryption_Info_pose
#define LL_ATON_Internal_Buffers_Info_network LL_ATON_Internal_Buffers_Info_pose

#include "../models/pose/generated/network.c"
