/* Wrapper to compile generated segmentation model with unique public symbols. */

#define LL_ATON_EC_Network_Init_network LL_ATON_EC_Network_Init_seg
#define LL_ATON_EC_Inference_Init_network LL_ATON_EC_Inference_Init_seg
#define LL_ATON_Set_User_Input_Buffer_network LL_ATON_Set_User_Input_Buffer_seg
#define LL_ATON_Get_User_Input_Buffer_network LL_ATON_Get_User_Input_Buffer_seg
#define LL_ATON_Set_User_Output_Buffer_network LL_ATON_Set_User_Output_Buffer_seg
#define LL_ATON_Get_User_Output_Buffer_network LL_ATON_Get_User_Output_Buffer_seg
#define LL_ATON_EpochBlockItems_network LL_ATON_EpochBlockItems_seg
#define LL_ATON_Output_Buffers_Info_network LL_ATON_Output_Buffers_Info_seg
#define LL_ATON_Input_Buffers_Info_network LL_ATON_Input_Buffers_Info_seg
#define LL_ATON_WeightEncryption_Info_network LL_ATON_WeightEncryption_Info_seg
#define LL_ATON_BlobEncryption_Info_network LL_ATON_BlobEncryption_Info_seg
#define LL_ATON_Internal_Buffers_Info_network LL_ATON_Internal_Buffers_Info_seg

#include "../models/seg/generated/network.c"
