
/* AUTOGENERATED DO NOT MODIFY */

/**
 ******************************************************************************
 * @file    stai_network.c
 * @author  SRA Artificial Intelligence & Embedded Architectures
 * @brief   Implementation of ST.AI platform public APIs for ATON
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stai_network.h"
#include "ll_aton_rt_user_api.h"
#include "ll_aton_util.h"
#include "ll_aton_version.h"

/* Status variables */
LL_ATON_DECLARE_NAMED_NN_INTERFACE(network);

/* Helper macros & functions */
#define __LL_ATON_STAI_CHECK_NETWORK_INTERFACE(nn_interface_ptr, ctx)                                                  \
  do                                                                                                                   \
  {                                                                                                                    \
    if ((nn_interface_ptr) != &NN_Interface_network)                                                     \
      __LL_ATON_STAI_SET_1ST_CTX_ERROR_AND_RETURN((ctx), STAI_ERROR_NETWORK_INVALID_CONTEXT_HANDLE);                   \
  } while (0)

static inline stai_return_code __ll_aton_stai_network_get_inputs_or_weights(stai_network *network,
                                                                                          stai_ptr *pointers,
                                                                                          stai_size *n_ptrs,
                                                                                          bool inputs)
{
  __LL_ATON_STAI_ACQUIRE_INTERFACE(nn_i_ptr, network);
  __LL_ATON_STAI_CHECK_NETWORK_INTERFACE(nn_i_ptr, (_stai_aton_context *)network);

  /* check parameters */
  if (!n_ptrs)
    __LL_ATON_STAI_SET_1ST_CTX_ERROR_AND_RETURN((_stai_aton_context *)network,
                                                STAI_ERROR_NETWORK_INVALID_API_ARGUMENTS);

  /* get input buffers */
  const LL_Buffer_InfoTypeDef *input_buffers = nn_i_ptr->input_buffers_info();

  /* copy buffer addresses */
  unsigned cnt = 0;
  if (input_buffers != NULL)
  {
    for (unsigned idx = 0; input_buffers[idx].name != NULL; idx++)
    {
      const LL_Buffer_InfoTypeDef *buffer_info = &input_buffers[idx];
      if (inputs == !buffer_info->is_param)
      {
        if (pointers)
        {
          if (buffer_info->is_user_allocated) // is it an user allocatable buffer
          {
            LL_ATON_ASSERT(buffer_info->offset_start ==
                           0); // user allocated buffers always have an offset equal to zero
            pointers[cnt] = LL_Buffer_addr_start(buffer_info); // user allocated buffers are saved with virtual address
            LL_ATON_ASSERT(((uintptr_t)pointers[cnt] % STAI_CACHE_USER_BUFFER_ALIGNMENT) == 0);
          }
          else // buffer is not user allocatable
          {
            pointers[cnt] = ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(LL_Buffer_addr_start(buffer_info));
          }
        }
        cnt++;
      }
    }
  }
  else
  {
    STAI_ASSERT((inputs ? STAI_NETWORK_IN_NUM : STAI_NETWORK_WEIGHTS_NUM) == 0);
  }
#ifndef NDEBUG
  if (inputs)
  {
    STAI_ASSERT(cnt == STAI_NETWORK_IN_NUM);
  }
  else
  {
    STAI_ASSERT(cnt == STAI_NETWORK_WEIGHTS_NUM);
  }
#endif // !NDEBUG

  /* save number of elements return value */
  if (inputs)
  {
    *n_ptrs = STAI_NETWORK_IN_NUM;
  }
  else
  {
    *n_ptrs = STAI_NETWORK_WEIGHTS_NUM;
  }

  return STAI_SUCCESS;
}

static inline stai_return_code __ll_aton_stai_network_get_outputs_or_activations(stai_network *network,
                                                                                               stai_ptr *pointers,
                                                                                               stai_size *n_ptrs,
                                                                                               bool outputs)
{
  /* check context & network interface handle */
  __LL_ATON_STAI_ACQUIRE_INTERFACE(nn_i_ptr, network);
  __LL_ATON_STAI_CHECK_NETWORK_INTERFACE(nn_i_ptr, (_stai_aton_context *)network);

  /* check parameters */
  if (!n_ptrs)
    __LL_ATON_STAI_SET_1ST_CTX_ERROR_AND_RETURN((_stai_aton_context *)network,
                                                STAI_ERROR_NETWORK_INVALID_API_ARGUMENTS);

  /* get output buffers */
  const LL_Buffer_InfoTypeDef *out_activ_buffers;
  if (outputs)
  {
    out_activ_buffers = nn_i_ptr->output_buffers_info();
  }
  else
  {
    out_activ_buffers = nn_i_ptr->internal_buffers_info();
  }

  /* copy buffer addresses */
  unsigned cnt = 0;
  if (out_activ_buffers != NULL)
  {
    for (unsigned idx = 0; out_activ_buffers[idx].name != NULL; idx++)
    {
      const LL_Buffer_InfoTypeDef *buffer_info = &out_activ_buffers[idx];
      STAI_ASSERT(!buffer_info->is_param); // may never happen
      if (pointers)
      {
        if (buffer_info->is_user_allocated) // is it a user allocatable buffer
        {
          LL_ATON_ASSERT(buffer_info->offset_start == 0); // user allocated buffers always have an offset equal to zero
          pointers[cnt] = LL_Buffer_addr_start(buffer_info); // user allocated buffers are saved with virtual address
          LL_ATON_ASSERT(((uintptr_t)pointers[cnt] % STAI_CACHE_USER_BUFFER_ALIGNMENT) == 0);
        }
        else // buffer is not user allocatable
        {
          pointers[cnt] = ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(LL_Buffer_addr_start(buffer_info));
        }
      }
      cnt++;
    }
  }
  else
  {
    STAI_ASSERT((outputs ? STAI_NETWORK_OUT_NUM : STAI_NETWORK_ACTIVATIONS_NUM) == 0);
  }
#ifndef NDEBUG
  if (outputs)
  {
    STAI_ASSERT(cnt == STAI_NETWORK_OUT_NUM);
  }
  else
  {
    STAI_ASSERT(cnt == STAI_NETWORK_ACTIVATIONS_NUM);
  }
#endif // !NDEBUG

  /* save number of elements return value */
  if (outputs)
  {
    *n_ptrs = STAI_NETWORK_OUT_NUM;
  }
  else
  {
    *n_ptrs = STAI_NETWORK_ACTIVATIONS_NUM;
  }

  return STAI_SUCCESS;
}

static inline stai_return_code __ll_aton_stai_network_set_inputs_or_weights(stai_network *network,
                                                                                          const stai_ptr *pointers,
                                                                                          const stai_size n_ptrs,
                                                                                          bool inputs)
{
  /* check context & network interface handle */
  __LL_ATON_STAI_ACQUIRE_INTERFACE(nn_i_ptr, network);
  __LL_ATON_STAI_CHECK_NETWORK_INTERFACE(nn_i_ptr, (_stai_aton_context *)network);

  /* get input buffers */
  const LL_Buffer_InfoTypeDef *input_buffers = nn_i_ptr->input_buffers_info();

  /* check values & addresses */
  LL_ATON_ASSERT(input_buffers != NULL);
  if (input_buffers && !pointers)
    __LL_ATON_STAI_SET_1ST_CTX_ERROR_AND_RETURN((_stai_aton_context *)network,
                                                STAI_ERROR_NETWORK_INVALID_API_ARGUMENTS);

  if (inputs)
  {
    if (n_ptrs != STAI_NETWORK_IN_NUM)
      __LL_ATON_STAI_SET_1ST_CTX_ERROR_AND_RETURN((_stai_aton_context *)network, STAI_ERROR_NETWORK_INVALID_IN_NUM);
  }
  else
  {
    if (n_ptrs != STAI_NETWORK_WEIGHTS_NUM)
      __LL_ATON_STAI_SET_1ST_CTX_ERROR_AND_RETURN((_stai_aton_context *)network,
                                                  STAI_ERROR_NETWORK_INVALID_WEIGHTS_NUM);
  }

  unsigned cnt = 0;
  if (input_buffers != NULL)
  {
    for (unsigned idx = 0; input_buffers[idx].name != NULL; idx++)
    {
      const LL_Buffer_InfoTypeDef *buffer_info = &input_buffers[idx];
      if (inputs == !buffer_info->is_param)
      {
        if (buffer_info->is_user_allocated) // is it an user allocatable buffer
        {
          LL_ATON_ASSERT(buffer_info->offset_start == 0); // user allocated buffers always have an offset equal to zero
          unsigned char **address_location = (unsigned char **)buffer_info->addr_base.p;
          unsigned char *new_address = pointers[cnt];

          if (((uintptr_t)new_address % STAI_CACHE_USER_BUFFER_ALIGNMENT) != 0) // check new address alignment
          {                                                                     // new address is not aligned
            __LL_ATON_STAI_SET_1ST_CTX_ERROR_AND_RETURN((_stai_aton_context *)network,
                                                        STAI_ERROR_INVALID_BUFFER_ALIGNMENT);
          }
          else // new address is aligned
          {
            LL_ATON_ASSERT(address_location != NULL);
            *address_location = new_address;
          }
        }
        else // buffer is not user allocatable
        {
          if (ATON_LIB_VIRTUAL_TO_PHYSICAL_ADDR(pointers[cnt]) != LL_Buffer_addr_start(buffer_info))
            __LL_ATON_STAI_SET_1ST_CTX_ERROR_AND_RETURN((_stai_aton_context *)network,
                                                        STAI_ERROR_NETWORK_INVALID_IN_PTR);
        }
        cnt++;
      }
    }
  }
  else
  {
    STAI_ASSERT((inputs ? STAI_NETWORK_IN_NUM : STAI_NETWORK_WEIGHTS_NUM) == 0);
  }
#ifndef NDEBUG
  if (inputs)
  {
    STAI_ASSERT(cnt == STAI_NETWORK_IN_NUM);
  }
  else
  {
    STAI_ASSERT(cnt == STAI_NETWORK_WEIGHTS_NUM);
  }
#endif // !NDEBUG

  return STAI_SUCCESS;
}

static inline stai_return_code __ll_aton_stai_network_set_outputs_or_activations(stai_network *network,
                                                                                               const stai_ptr *pointers,
                                                                                               const stai_size n_ptrs,
                                                                                               bool outputs)
{
  /* check context & network interface handle */
  __LL_ATON_STAI_ACQUIRE_INTERFACE(nn_i_ptr, network);
  __LL_ATON_STAI_CHECK_NETWORK_INTERFACE(nn_i_ptr, (_stai_aton_context *)network);

  /* get output buffers */
  const LL_Buffer_InfoTypeDef *out_activ_buffers;
  if (outputs)
  {
    out_activ_buffers = nn_i_ptr->output_buffers_info();
  }
  else
  {
    out_activ_buffers = nn_i_ptr->output_buffers_info();
  }

  /* check values & addresses */
  if (out_activ_buffers && !pointers)
    __LL_ATON_STAI_SET_1ST_CTX_ERROR_AND_RETURN((_stai_aton_context *)network,
                                                STAI_ERROR_NETWORK_INVALID_API_ARGUMENTS);

  if (outputs)
  {
    if (n_ptrs != STAI_NETWORK_OUT_NUM)
      __LL_ATON_STAI_SET_1ST_CTX_ERROR_AND_RETURN((_stai_aton_context *)network, STAI_ERROR_NETWORK_INVALID_OUT_NUM);
  }
  else
  {
    if (n_ptrs != STAI_NETWORK_ACTIVATIONS_NUM)
      __LL_ATON_STAI_SET_1ST_CTX_ERROR_AND_RETURN((_stai_aton_context *)network, STAI_ERROR_NETWORK_INVALID_OUT_NUM);
  }

  unsigned cnt = 0;
  if (out_activ_buffers != NULL)
  {
    for (unsigned idx = 0; out_activ_buffers[idx].name != NULL; idx++)
    {
      const LL_Buffer_InfoTypeDef *buffer_info = &out_activ_buffers[idx];
      if (buffer_info->is_user_allocated) // is it an user allocatable buffer
      {
        LL_ATON_ASSERT(buffer_info->offset_start == 0); // user allocated buffers always have an offset equal to zero
        unsigned char **address_location = (unsigned char **)buffer_info->addr_base.p;
        unsigned char *new_address = pointers[cnt];

        if (((uintptr_t)new_address % STAI_CACHE_USER_BUFFER_ALIGNMENT) != 0) // check new address alignment
        {                                                                     // new address is not aligned
          __LL_ATON_STAI_SET_1ST_CTX_ERROR_AND_RETURN((_stai_aton_context *)network,
                                                      STAI_ERROR_INVALID_BUFFER_ALIGNMENT);
        }
        else // new address is aligned
        {
          LL_ATON_ASSERT(address_location != NULL);
          *address_location = new_address;
        }
      }
      else // buffer is not user allocatable
      {
        STAI_ASSERT(!buffer_info->is_param);
        if (ATON_LIB_VIRTUAL_TO_PHYSICAL_ADDR(pointers[cnt]) != LL_Buffer_addr_start(out_activ_buffers))
          __LL_ATON_STAI_SET_1ST_CTX_ERROR_AND_RETURN((_stai_aton_context *)network,
                                                      STAI_ERROR_NETWORK_INVALID_OUT_PTR);
      }
      cnt++;
    }
  }
  else
  {
    STAI_ASSERT((outputs ? STAI_NETWORK_OUT_NUM : STAI_NETWORK_ACTIVATIONS_NUM) == 0);
  }
#ifndef NDEBUG
  if (outputs)
  {
    STAI_ASSERT(cnt == STAI_NETWORK_OUT_NUM);
  }
  else
  {
    STAI_ASSERT(cnt == STAI_NETWORK_ACTIVATIONS_NUM);
  }
#endif // !NDEBUG

  return STAI_SUCCESS;
}

/*****************************************************************************/
/*  Network management APIs  */
STAI_API_ENTRY
stai_return_code stai_network_init(stai_network *network)
{
  /* check context handle */
  if (!network)
    return STAI_ERROR_NETWORK_INVALID_CONTEXT_HANDLE;

  _stai_aton_context *ctx = (_stai_aton_context *)network;
  if (ctx->network_instance.network != NULL) // already initialized
    __LL_ATON_STAI_SET_1ST_CTX_ERROR_AND_RETURN(ctx, STAI_ERROR_NETWORK_INVALID_CONTEXT_HANDLE);

  ctx->network_instance.network = (const NN_Interface_TypeDef *)&NN_Interface_network;
  ctx->exec_status = STAI_SUCCESS;
  ctx->first_error = STAI_SUCCESS;

  __ll_aton_stai_init_network_instance(ctx);

  return STAI_SUCCESS;
}

STAI_API_ENTRY
stai_return_code stai_network_deinit(stai_network *network)
{
  __LL_ATON_STAI_ACQUIRE_INTERFACE(nn_i_ptr, network);
  __LL_ATON_STAI_CHECK_NETWORK_INTERFACE(nn_i_ptr, (_stai_aton_context *)network);
  _stai_aton_context *ctx = (_stai_aton_context *)network;

  if (ctx->exec_status != STAI_DONE && ctx->exec_status != STAI_SUCCESS)
  {
    __LL_ATON_STAI_SET_1ST_CTX_ERROR_AND_RETURN(ctx, STAI_ERROR_NETWORK_STILL_RUNNING);
  }

  __ll_aton_stai_deinit_network_instance(ctx);

  ctx->network_instance.network = NULL;

  ctx->callback = NULL;
  ctx->callback_cookie = NULL;
  LL_ATON_RT_SetNetworkCallback(&ctx->network_instance, NULL);

  ctx->exec_status = STAI_SUCCESS;
  ctx->first_error = STAI_SUCCESS;

  return STAI_SUCCESS;
}

STAI_API_ENTRY
stai_return_code stai_network_run(stai_network *network, const stai_run_mode mode)
{
  /* check context & network interface handle */
  __LL_ATON_STAI_ACQUIRE_INTERFACE(nn_i_ptr, network);
  __LL_ATON_STAI_CHECK_NETWORK_INTERFACE(nn_i_ptr, (_stai_aton_context *)network);

  return __ll_aton_stai_run(network, mode);
}

STAI_API_ENTRY
stai_return_code stai_network_train(stai_network *network, const stai_run_mode mode)
{
  LL_ATON_LIB_UNUSED(mode);

  /* check context & network interface handle */
  __LL_ATON_STAI_ACQUIRE_INTERFACE(nn_i_ptr, network);
  __LL_ATON_STAI_CHECK_NETWORK_INTERFACE(nn_i_ptr, (_stai_aton_context *)network);

  __LL_ATON_STAI_SET_1ST_CTX_ERROR_AND_RETURN((_stai_aton_context *)network, STAI_ERROR_NOT_IMPLEMENTED);
}

/*****************************************************************************/
/*  Getters APIs  */
STAI_API_ENTRY
stai_return_code stai_network_get_inputs(stai_network *network, stai_ptr *inputs, stai_size *n_inputs)
{
  return __ll_aton_stai_network_get_inputs_or_weights(network, inputs, n_inputs, true);
}

STAI_API_ENTRY
stai_return_code stai_network_get_weights(stai_network *network, stai_ptr *weights, stai_size *n_weights)
{
  return __ll_aton_stai_network_get_inputs_or_weights(network, weights, n_weights, false);
}

STAI_API_ENTRY
stai_return_code stai_network_get_outputs(stai_network *network, stai_ptr *outputs, stai_size *n_outputs)
{
  return __ll_aton_stai_network_get_outputs_or_activations(network, outputs, n_outputs, true);
}

STAI_API_ENTRY
stai_return_code stai_network_get_activations(stai_network *network, stai_ptr *activations,
                                                            stai_size *n_activations)
{
  return __ll_aton_stai_network_get_outputs_or_activations(network, activations, n_activations, false);
}

static const stai_network_info __stai_network_network_info;
STAI_API_ENTRY
stai_return_code stai_network_get_info(stai_network *network, stai_network_info *info)
{
  /* check context & network interface handle */
  __LL_ATON_STAI_ACQUIRE_INTERFACE(nn_i_ptr, network);
  __LL_ATON_STAI_CHECK_NETWORK_INTERFACE(nn_i_ptr, (_stai_aton_context *)network);

  // Copy of network info struct
  *info = __stai_network_network_info;

  return STAI_SUCCESS;
}

STAI_API_ENTRY
stai_return_code stai_network_get_states(stai_network *network, stai_ptr *states, stai_size *n_states)
{
  LL_ATON_LIB_UNUSED(states);

  /* check context & network interface handle */
  __LL_ATON_STAI_ACQUIRE_INTERFACE(nn_i_ptr, network);
  __LL_ATON_STAI_CHECK_NETWORK_INTERFACE(nn_i_ptr, (_stai_aton_context *)network);

  *n_states = 0;
  return STAI_SUCCESS;
}

STAI_API_ENTRY
stai_return_code stai_network_get_error(stai_network *network)
{
  __LL_ATON_STAI_ACQUIRE_INTERFACE(nn_i_ptr, network);
  __LL_ATON_STAI_CHECK_NETWORK_INTERFACE(nn_i_ptr, (_stai_aton_context *)network);
  _stai_aton_context *ctx = (_stai_aton_context *)network;

  // return 1st generated error or STAI_SUCCESS if no errors so far
  return ctx->first_error;
}

/*****************************************************************************/
/*  Setters APIs  */
STAI_API_ENTRY
stai_return_code stai_network_set_inputs(stai_network *network, const stai_ptr *inputs,
                                                       const stai_size n_inputs)
{
  return __ll_aton_stai_network_set_inputs_or_weights(network, inputs, n_inputs, true);
}

STAI_API_ENTRY
stai_return_code stai_network_set_weights(stai_network *network, const stai_ptr *weights,
                                                        const stai_size n_weights)
{
  return __ll_aton_stai_network_set_inputs_or_weights(network, weights, n_weights, false);
}

STAI_API_ENTRY
stai_return_code stai_network_set_outputs(stai_network *network, const stai_ptr *outputs,
                                                        const stai_size n_outputs)
{
  return __ll_aton_stai_network_set_outputs_or_activations(network, outputs, n_outputs, true);
}

STAI_API_ENTRY
stai_return_code stai_network_set_activations(stai_network *network, const stai_ptr *activations,
                                                            const stai_size n_activations)
{
  return __ll_aton_stai_network_set_outputs_or_activations(network, activations, n_activations, false);
}

STAI_API_ENTRY
stai_return_code stai_network_set_states(stai_network *network, const stai_ptr *states,
                                                       const stai_size n_states)
{
  LL_ATON_LIB_UNUSED(states);

  /* check context & network interface handle */
  __LL_ATON_STAI_ACQUIRE_INTERFACE(nn_i_ptr, network);
  __LL_ATON_STAI_CHECK_NETWORK_INTERFACE(nn_i_ptr, (_stai_aton_context *)network);

  if (n_states != 0)
    __LL_ATON_STAI_SET_1ST_CTX_ERROR_AND_RETURN((_stai_aton_context *)network, STAI_ERROR_NETWORK_INVALID_STATES_NUM);
  else
    return STAI_SUCCESS;
}

STAI_API_ENTRY
stai_return_code stai_network_set_callback(stai_network *network, const stai_event_cb cb, void *cb_cookie)
{
  if (network == NULL)
  {
    return STAI_ERROR_NETWORK_INVALID_CONTEXT_HANDLE;
  }

  _stai_aton_context *nn_ctx = (_stai_aton_context *)network;

  if ((nn_ctx->network_instance.network != NULL) &&
      (nn_ctx->network_instance.network != &NN_Interface_network))
  {
    __LL_ATON_STAI_SET_1ST_CTX_ERROR_AND_RETURN(nn_ctx, STAI_ERROR_NETWORK_INVALID_CONTEXT_HANDLE);
  }

  nn_ctx->callback = cb;
  nn_ctx->callback_cookie = cb_cookie;

  LL_ATON_RT_SetNetworkCallback(&nn_ctx->network_instance,
                                (cb != NULL) ? _stai_aton_internal_epoch_block_callback : NULL);

  return STAI_SUCCESS;
}

/***************************************************************************/
/*  Extended ATON Target Specific APIs  */
STAI_API_ENTRY
stai_return_code stai_ext_network_run_continue(stai_network *network)
{
  _stai_aton_context *nn_ctx = (_stai_aton_context *)network;
  if (nn_ctx == NULL)
  {
    __LL_ATON_STAI_SET_1ST_CTX_ERROR_AND_RETURN((_stai_aton_context *)network,
                                                STAI_ERROR_NETWORK_INVALID_CONTEXT_HANDLE);
  }

  __LL_ATON_STAI_ACQUIRE_INTERFACE(nn_i_ptr, network);
  __LL_ATON_STAI_CHECK_NETWORK_INTERFACE(nn_i_ptr, nn_ctx);

  if (nn_ctx->network_instance.exec_state.current_epoch_block == NULL)
  {
    __LL_ATON_STAI_SET_1ST_CTX_ERROR_AND_RETURN(nn_ctx, STAI_ERROR_NETWORK_INVALID_API_ARGUMENTS);
  }

  __LL_ATON_START_CONT_EXEC(&nn_ctx->network_instance);
}

STAI_API_ENTRY
stai_return_code stai_ext_network_get_nn_run_status(stai_network *network)
{
  /* check context & network interface handle */
  __LL_ATON_STAI_ACQUIRE_INTERFACE(nn_i_ptr, network);
  __LL_ATON_STAI_CHECK_NETWORK_INTERFACE(nn_i_ptr, (_stai_aton_context *)network);

  /* get current execution status */
  STAI_ASSERT(network != NULL);
  _stai_aton_context *stai_nn_ctx =
      (_stai_aton_context *)((void *)network) - offsetof(_stai_aton_context, network_instance);
  stai_return_code current_exec_status = __ll_aton_stai_get_execution_status(stai_nn_ctx);

  return current_exec_status;
}

STAI_API_ENTRY
stai_return_code stai_ext_network_new_inference(stai_network *network)
{
  return __ll_aton_stai_reset(network);
}

// clang-format off
/***************************************************************************/
/*  Auto-generated network information structure  */
static const stai_network_info __stai_network_network_info = {
    // Still missing fields are:
    // - `.model_signature = STAI_NETWORK_SIGNATURE`,     // TODO: generate this macro in `*.h` file
    // - `.c_model_signature = STAI_NETWORK_C_SIGNATURE`, // TODO: generate this macro in `*.h` file
    // - `.n_macc =` ???,

    .c_model_name = STAI_NETWORK_C_MODEL_NAME,
    .c_compile_datetime = __DATE__ " " __TIME__,

    .runtime_version = STAI_INIT_VERSION(LL_ATON_VERSION_MAJOR, LL_ATON_VERSION_MINOR, LL_ATON_VERSION_MICRO),
    .tool_version = STAI_INIT_VERSION(STAI_TOOLS_VERSION_MAJOR, STAI_TOOLS_VERSION_MINOR, STAI_TOOLS_VERSION_MICRO),
    .api_version = STAI_INIT_VERSION(STAI_API_VERSION_MAJOR, STAI_API_VERSION_MINOR, STAI_API_VERSION_MICRO),

    .flags = STAI_NETWORK_FLAGS,

    .n_inputs = STAI_NETWORK_IN_NUM, 
    .n_outputs = STAI_NETWORK_OUT_NUM,
    .n_activations = STAI_NETWORK_ACTIVATIONS_NUM, 
    .n_weights = STAI_NETWORK_WEIGHTS_NUM,
    .n_states = STAI_NETWORK_STATES_NUM,

    .c_model_datetime = "2026-03-16 19:40:45",

    .n_nodes = 372,

    .inputs = (stai_tensor[STAI_NETWORK_IN_NUM]) {
      STAI_INIT_TENSOR(
        STAI_NETWORK_IN_1_NAME,
        STAI_NETWORK_IN_1_FLAGS,
        STAI_NETWORK_IN_1_FORMAT,
        STAI_NETWORK_IN_1_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_IN_1_RANK, STAI_NETWORK_IN_1_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
    },
    .outputs = (stai_tensor[STAI_NETWORK_OUT_NUM]) {
      STAI_INIT_TENSOR(
        STAI_NETWORK_OUT_1_NAME,
        STAI_NETWORK_OUT_1_FLAGS,
        STAI_NETWORK_OUT_1_FORMAT,
        STAI_NETWORK_OUT_1_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_OUT_1_RANK, STAI_NETWORK_OUT_1_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
    },
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
    .weights = (stai_tensor[STAI_NETWORK_WEIGHTS_NUM]) {
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_1_NAME,
        STAI_NETWORK_WEIGHTS_1_FLAGS,
        STAI_NETWORK_WEIGHTS_1_FORMAT,
        STAI_NETWORK_WEIGHTS_1_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_1_RANK, STAI_NETWORK_WEIGHTS_1_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_2_NAME,
        STAI_NETWORK_WEIGHTS_2_FLAGS,
        STAI_NETWORK_WEIGHTS_2_FORMAT,
        STAI_NETWORK_WEIGHTS_2_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_2_RANK, STAI_NETWORK_WEIGHTS_2_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_3_NAME,
        STAI_NETWORK_WEIGHTS_3_FLAGS,
        STAI_NETWORK_WEIGHTS_3_FORMAT,
        STAI_NETWORK_WEIGHTS_3_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_3_RANK, STAI_NETWORK_WEIGHTS_3_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_4_NAME,
        STAI_NETWORK_WEIGHTS_4_FLAGS,
        STAI_NETWORK_WEIGHTS_4_FORMAT,
        STAI_NETWORK_WEIGHTS_4_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_4_RANK, STAI_NETWORK_WEIGHTS_4_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_5_NAME,
        STAI_NETWORK_WEIGHTS_5_FLAGS,
        STAI_NETWORK_WEIGHTS_5_FORMAT,
        STAI_NETWORK_WEIGHTS_5_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_5_RANK, STAI_NETWORK_WEIGHTS_5_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_6_NAME,
        STAI_NETWORK_WEIGHTS_6_FLAGS,
        STAI_NETWORK_WEIGHTS_6_FORMAT,
        STAI_NETWORK_WEIGHTS_6_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_6_RANK, STAI_NETWORK_WEIGHTS_6_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_7_NAME,
        STAI_NETWORK_WEIGHTS_7_FLAGS,
        STAI_NETWORK_WEIGHTS_7_FORMAT,
        STAI_NETWORK_WEIGHTS_7_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_7_RANK, STAI_NETWORK_WEIGHTS_7_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_8_NAME,
        STAI_NETWORK_WEIGHTS_8_FLAGS,
        STAI_NETWORK_WEIGHTS_8_FORMAT,
        STAI_NETWORK_WEIGHTS_8_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_8_RANK, STAI_NETWORK_WEIGHTS_8_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_9_NAME,
        STAI_NETWORK_WEIGHTS_9_FLAGS,
        STAI_NETWORK_WEIGHTS_9_FORMAT,
        STAI_NETWORK_WEIGHTS_9_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_9_RANK, STAI_NETWORK_WEIGHTS_9_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_10_NAME,
        STAI_NETWORK_WEIGHTS_10_FLAGS,
        STAI_NETWORK_WEIGHTS_10_FORMAT,
        STAI_NETWORK_WEIGHTS_10_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_10_RANK, STAI_NETWORK_WEIGHTS_10_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_11_NAME,
        STAI_NETWORK_WEIGHTS_11_FLAGS,
        STAI_NETWORK_WEIGHTS_11_FORMAT,
        STAI_NETWORK_WEIGHTS_11_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_11_RANK, STAI_NETWORK_WEIGHTS_11_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_12_NAME,
        STAI_NETWORK_WEIGHTS_12_FLAGS,
        STAI_NETWORK_WEIGHTS_12_FORMAT,
        STAI_NETWORK_WEIGHTS_12_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_12_RANK, STAI_NETWORK_WEIGHTS_12_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_13_NAME,
        STAI_NETWORK_WEIGHTS_13_FLAGS,
        STAI_NETWORK_WEIGHTS_13_FORMAT,
        STAI_NETWORK_WEIGHTS_13_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_13_RANK, STAI_NETWORK_WEIGHTS_13_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_14_NAME,
        STAI_NETWORK_WEIGHTS_14_FLAGS,
        STAI_NETWORK_WEIGHTS_14_FORMAT,
        STAI_NETWORK_WEIGHTS_14_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_14_RANK, STAI_NETWORK_WEIGHTS_14_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_15_NAME,
        STAI_NETWORK_WEIGHTS_15_FLAGS,
        STAI_NETWORK_WEIGHTS_15_FORMAT,
        STAI_NETWORK_WEIGHTS_15_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_15_RANK, STAI_NETWORK_WEIGHTS_15_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_16_NAME,
        STAI_NETWORK_WEIGHTS_16_FLAGS,
        STAI_NETWORK_WEIGHTS_16_FORMAT,
        STAI_NETWORK_WEIGHTS_16_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_16_RANK, STAI_NETWORK_WEIGHTS_16_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_17_NAME,
        STAI_NETWORK_WEIGHTS_17_FLAGS,
        STAI_NETWORK_WEIGHTS_17_FORMAT,
        STAI_NETWORK_WEIGHTS_17_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_17_RANK, STAI_NETWORK_WEIGHTS_17_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_18_NAME,
        STAI_NETWORK_WEIGHTS_18_FLAGS,
        STAI_NETWORK_WEIGHTS_18_FORMAT,
        STAI_NETWORK_WEIGHTS_18_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_18_RANK, STAI_NETWORK_WEIGHTS_18_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_19_NAME,
        STAI_NETWORK_WEIGHTS_19_FLAGS,
        STAI_NETWORK_WEIGHTS_19_FORMAT,
        STAI_NETWORK_WEIGHTS_19_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_19_RANK, STAI_NETWORK_WEIGHTS_19_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_20_NAME,
        STAI_NETWORK_WEIGHTS_20_FLAGS,
        STAI_NETWORK_WEIGHTS_20_FORMAT,
        STAI_NETWORK_WEIGHTS_20_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_20_RANK, STAI_NETWORK_WEIGHTS_20_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_21_NAME,
        STAI_NETWORK_WEIGHTS_21_FLAGS,
        STAI_NETWORK_WEIGHTS_21_FORMAT,
        STAI_NETWORK_WEIGHTS_21_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_21_RANK, STAI_NETWORK_WEIGHTS_21_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_22_NAME,
        STAI_NETWORK_WEIGHTS_22_FLAGS,
        STAI_NETWORK_WEIGHTS_22_FORMAT,
        STAI_NETWORK_WEIGHTS_22_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_22_RANK, STAI_NETWORK_WEIGHTS_22_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_23_NAME,
        STAI_NETWORK_WEIGHTS_23_FLAGS,
        STAI_NETWORK_WEIGHTS_23_FORMAT,
        STAI_NETWORK_WEIGHTS_23_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_23_RANK, STAI_NETWORK_WEIGHTS_23_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_24_NAME,
        STAI_NETWORK_WEIGHTS_24_FLAGS,
        STAI_NETWORK_WEIGHTS_24_FORMAT,
        STAI_NETWORK_WEIGHTS_24_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_24_RANK, STAI_NETWORK_WEIGHTS_24_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_25_NAME,
        STAI_NETWORK_WEIGHTS_25_FLAGS,
        STAI_NETWORK_WEIGHTS_25_FORMAT,
        STAI_NETWORK_WEIGHTS_25_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_25_RANK, STAI_NETWORK_WEIGHTS_25_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_26_NAME,
        STAI_NETWORK_WEIGHTS_26_FLAGS,
        STAI_NETWORK_WEIGHTS_26_FORMAT,
        STAI_NETWORK_WEIGHTS_26_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_26_RANK, STAI_NETWORK_WEIGHTS_26_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_27_NAME,
        STAI_NETWORK_WEIGHTS_27_FLAGS,
        STAI_NETWORK_WEIGHTS_27_FORMAT,
        STAI_NETWORK_WEIGHTS_27_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_27_RANK, STAI_NETWORK_WEIGHTS_27_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_28_NAME,
        STAI_NETWORK_WEIGHTS_28_FLAGS,
        STAI_NETWORK_WEIGHTS_28_FORMAT,
        STAI_NETWORK_WEIGHTS_28_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_28_RANK, STAI_NETWORK_WEIGHTS_28_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_29_NAME,
        STAI_NETWORK_WEIGHTS_29_FLAGS,
        STAI_NETWORK_WEIGHTS_29_FORMAT,
        STAI_NETWORK_WEIGHTS_29_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_29_RANK, STAI_NETWORK_WEIGHTS_29_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_30_NAME,
        STAI_NETWORK_WEIGHTS_30_FLAGS,
        STAI_NETWORK_WEIGHTS_30_FORMAT,
        STAI_NETWORK_WEIGHTS_30_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_30_RANK, STAI_NETWORK_WEIGHTS_30_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_31_NAME,
        STAI_NETWORK_WEIGHTS_31_FLAGS,
        STAI_NETWORK_WEIGHTS_31_FORMAT,
        STAI_NETWORK_WEIGHTS_31_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_31_RANK, STAI_NETWORK_WEIGHTS_31_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_32_NAME,
        STAI_NETWORK_WEIGHTS_32_FLAGS,
        STAI_NETWORK_WEIGHTS_32_FORMAT,
        STAI_NETWORK_WEIGHTS_32_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_32_RANK, STAI_NETWORK_WEIGHTS_32_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_33_NAME,
        STAI_NETWORK_WEIGHTS_33_FLAGS,
        STAI_NETWORK_WEIGHTS_33_FORMAT,
        STAI_NETWORK_WEIGHTS_33_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_33_RANK, STAI_NETWORK_WEIGHTS_33_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_34_NAME,
        STAI_NETWORK_WEIGHTS_34_FLAGS,
        STAI_NETWORK_WEIGHTS_34_FORMAT,
        STAI_NETWORK_WEIGHTS_34_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_34_RANK, STAI_NETWORK_WEIGHTS_34_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_35_NAME,
        STAI_NETWORK_WEIGHTS_35_FLAGS,
        STAI_NETWORK_WEIGHTS_35_FORMAT,
        STAI_NETWORK_WEIGHTS_35_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_35_RANK, STAI_NETWORK_WEIGHTS_35_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_36_NAME,
        STAI_NETWORK_WEIGHTS_36_FLAGS,
        STAI_NETWORK_WEIGHTS_36_FORMAT,
        STAI_NETWORK_WEIGHTS_36_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_36_RANK, STAI_NETWORK_WEIGHTS_36_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_37_NAME,
        STAI_NETWORK_WEIGHTS_37_FLAGS,
        STAI_NETWORK_WEIGHTS_37_FORMAT,
        STAI_NETWORK_WEIGHTS_37_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_37_RANK, STAI_NETWORK_WEIGHTS_37_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_38_NAME,
        STAI_NETWORK_WEIGHTS_38_FLAGS,
        STAI_NETWORK_WEIGHTS_38_FORMAT,
        STAI_NETWORK_WEIGHTS_38_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_38_RANK, STAI_NETWORK_WEIGHTS_38_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_39_NAME,
        STAI_NETWORK_WEIGHTS_39_FLAGS,
        STAI_NETWORK_WEIGHTS_39_FORMAT,
        STAI_NETWORK_WEIGHTS_39_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_39_RANK, STAI_NETWORK_WEIGHTS_39_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_40_NAME,
        STAI_NETWORK_WEIGHTS_40_FLAGS,
        STAI_NETWORK_WEIGHTS_40_FORMAT,
        STAI_NETWORK_WEIGHTS_40_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_40_RANK, STAI_NETWORK_WEIGHTS_40_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_41_NAME,
        STAI_NETWORK_WEIGHTS_41_FLAGS,
        STAI_NETWORK_WEIGHTS_41_FORMAT,
        STAI_NETWORK_WEIGHTS_41_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_41_RANK, STAI_NETWORK_WEIGHTS_41_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_42_NAME,
        STAI_NETWORK_WEIGHTS_42_FLAGS,
        STAI_NETWORK_WEIGHTS_42_FORMAT,
        STAI_NETWORK_WEIGHTS_42_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_42_RANK, STAI_NETWORK_WEIGHTS_42_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_43_NAME,
        STAI_NETWORK_WEIGHTS_43_FLAGS,
        STAI_NETWORK_WEIGHTS_43_FORMAT,
        STAI_NETWORK_WEIGHTS_43_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_43_RANK, STAI_NETWORK_WEIGHTS_43_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_44_NAME,
        STAI_NETWORK_WEIGHTS_44_FLAGS,
        STAI_NETWORK_WEIGHTS_44_FORMAT,
        STAI_NETWORK_WEIGHTS_44_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_44_RANK, STAI_NETWORK_WEIGHTS_44_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_45_NAME,
        STAI_NETWORK_WEIGHTS_45_FLAGS,
        STAI_NETWORK_WEIGHTS_45_FORMAT,
        STAI_NETWORK_WEIGHTS_45_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_45_RANK, STAI_NETWORK_WEIGHTS_45_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_46_NAME,
        STAI_NETWORK_WEIGHTS_46_FLAGS,
        STAI_NETWORK_WEIGHTS_46_FORMAT,
        STAI_NETWORK_WEIGHTS_46_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_46_RANK, STAI_NETWORK_WEIGHTS_46_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_47_NAME,
        STAI_NETWORK_WEIGHTS_47_FLAGS,
        STAI_NETWORK_WEIGHTS_47_FORMAT,
        STAI_NETWORK_WEIGHTS_47_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_47_RANK, STAI_NETWORK_WEIGHTS_47_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_48_NAME,
        STAI_NETWORK_WEIGHTS_48_FLAGS,
        STAI_NETWORK_WEIGHTS_48_FORMAT,
        STAI_NETWORK_WEIGHTS_48_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_48_RANK, STAI_NETWORK_WEIGHTS_48_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_49_NAME,
        STAI_NETWORK_WEIGHTS_49_FLAGS,
        STAI_NETWORK_WEIGHTS_49_FORMAT,
        STAI_NETWORK_WEIGHTS_49_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_49_RANK, STAI_NETWORK_WEIGHTS_49_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_50_NAME,
        STAI_NETWORK_WEIGHTS_50_FLAGS,
        STAI_NETWORK_WEIGHTS_50_FORMAT,
        STAI_NETWORK_WEIGHTS_50_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_50_RANK, STAI_NETWORK_WEIGHTS_50_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_51_NAME,
        STAI_NETWORK_WEIGHTS_51_FLAGS,
        STAI_NETWORK_WEIGHTS_51_FORMAT,
        STAI_NETWORK_WEIGHTS_51_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_51_RANK, STAI_NETWORK_WEIGHTS_51_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_52_NAME,
        STAI_NETWORK_WEIGHTS_52_FLAGS,
        STAI_NETWORK_WEIGHTS_52_FORMAT,
        STAI_NETWORK_WEIGHTS_52_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_52_RANK, STAI_NETWORK_WEIGHTS_52_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_53_NAME,
        STAI_NETWORK_WEIGHTS_53_FLAGS,
        STAI_NETWORK_WEIGHTS_53_FORMAT,
        STAI_NETWORK_WEIGHTS_53_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_53_RANK, STAI_NETWORK_WEIGHTS_53_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_54_NAME,
        STAI_NETWORK_WEIGHTS_54_FLAGS,
        STAI_NETWORK_WEIGHTS_54_FORMAT,
        STAI_NETWORK_WEIGHTS_54_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_54_RANK, STAI_NETWORK_WEIGHTS_54_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_55_NAME,
        STAI_NETWORK_WEIGHTS_55_FLAGS,
        STAI_NETWORK_WEIGHTS_55_FORMAT,
        STAI_NETWORK_WEIGHTS_55_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_55_RANK, STAI_NETWORK_WEIGHTS_55_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_56_NAME,
        STAI_NETWORK_WEIGHTS_56_FLAGS,
        STAI_NETWORK_WEIGHTS_56_FORMAT,
        STAI_NETWORK_WEIGHTS_56_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_56_RANK, STAI_NETWORK_WEIGHTS_56_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_57_NAME,
        STAI_NETWORK_WEIGHTS_57_FLAGS,
        STAI_NETWORK_WEIGHTS_57_FORMAT,
        STAI_NETWORK_WEIGHTS_57_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_57_RANK, STAI_NETWORK_WEIGHTS_57_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_58_NAME,
        STAI_NETWORK_WEIGHTS_58_FLAGS,
        STAI_NETWORK_WEIGHTS_58_FORMAT,
        STAI_NETWORK_WEIGHTS_58_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_58_RANK, STAI_NETWORK_WEIGHTS_58_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_59_NAME,
        STAI_NETWORK_WEIGHTS_59_FLAGS,
        STAI_NETWORK_WEIGHTS_59_FORMAT,
        STAI_NETWORK_WEIGHTS_59_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_59_RANK, STAI_NETWORK_WEIGHTS_59_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_60_NAME,
        STAI_NETWORK_WEIGHTS_60_FLAGS,
        STAI_NETWORK_WEIGHTS_60_FORMAT,
        STAI_NETWORK_WEIGHTS_60_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_60_RANK, STAI_NETWORK_WEIGHTS_60_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_61_NAME,
        STAI_NETWORK_WEIGHTS_61_FLAGS,
        STAI_NETWORK_WEIGHTS_61_FORMAT,
        STAI_NETWORK_WEIGHTS_61_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_61_RANK, STAI_NETWORK_WEIGHTS_61_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_62_NAME,
        STAI_NETWORK_WEIGHTS_62_FLAGS,
        STAI_NETWORK_WEIGHTS_62_FORMAT,
        STAI_NETWORK_WEIGHTS_62_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_62_RANK, STAI_NETWORK_WEIGHTS_62_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_63_NAME,
        STAI_NETWORK_WEIGHTS_63_FLAGS,
        STAI_NETWORK_WEIGHTS_63_FORMAT,
        STAI_NETWORK_WEIGHTS_63_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_63_RANK, STAI_NETWORK_WEIGHTS_63_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_64_NAME,
        STAI_NETWORK_WEIGHTS_64_FLAGS,
        STAI_NETWORK_WEIGHTS_64_FORMAT,
        STAI_NETWORK_WEIGHTS_64_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_64_RANK, STAI_NETWORK_WEIGHTS_64_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_65_NAME,
        STAI_NETWORK_WEIGHTS_65_FLAGS,
        STAI_NETWORK_WEIGHTS_65_FORMAT,
        STAI_NETWORK_WEIGHTS_65_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_65_RANK, STAI_NETWORK_WEIGHTS_65_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_66_NAME,
        STAI_NETWORK_WEIGHTS_66_FLAGS,
        STAI_NETWORK_WEIGHTS_66_FORMAT,
        STAI_NETWORK_WEIGHTS_66_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_66_RANK, STAI_NETWORK_WEIGHTS_66_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_67_NAME,
        STAI_NETWORK_WEIGHTS_67_FLAGS,
        STAI_NETWORK_WEIGHTS_67_FORMAT,
        STAI_NETWORK_WEIGHTS_67_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_67_RANK, STAI_NETWORK_WEIGHTS_67_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_68_NAME,
        STAI_NETWORK_WEIGHTS_68_FLAGS,
        STAI_NETWORK_WEIGHTS_68_FORMAT,
        STAI_NETWORK_WEIGHTS_68_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_68_RANK, STAI_NETWORK_WEIGHTS_68_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_69_NAME,
        STAI_NETWORK_WEIGHTS_69_FLAGS,
        STAI_NETWORK_WEIGHTS_69_FORMAT,
        STAI_NETWORK_WEIGHTS_69_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_69_RANK, STAI_NETWORK_WEIGHTS_69_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_70_NAME,
        STAI_NETWORK_WEIGHTS_70_FLAGS,
        STAI_NETWORK_WEIGHTS_70_FORMAT,
        STAI_NETWORK_WEIGHTS_70_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_70_RANK, STAI_NETWORK_WEIGHTS_70_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_71_NAME,
        STAI_NETWORK_WEIGHTS_71_FLAGS,
        STAI_NETWORK_WEIGHTS_71_FORMAT,
        STAI_NETWORK_WEIGHTS_71_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_71_RANK, STAI_NETWORK_WEIGHTS_71_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_72_NAME,
        STAI_NETWORK_WEIGHTS_72_FLAGS,
        STAI_NETWORK_WEIGHTS_72_FORMAT,
        STAI_NETWORK_WEIGHTS_72_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_72_RANK, STAI_NETWORK_WEIGHTS_72_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_73_NAME,
        STAI_NETWORK_WEIGHTS_73_FLAGS,
        STAI_NETWORK_WEIGHTS_73_FORMAT,
        STAI_NETWORK_WEIGHTS_73_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_73_RANK, STAI_NETWORK_WEIGHTS_73_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_74_NAME,
        STAI_NETWORK_WEIGHTS_74_FLAGS,
        STAI_NETWORK_WEIGHTS_74_FORMAT,
        STAI_NETWORK_WEIGHTS_74_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_74_RANK, STAI_NETWORK_WEIGHTS_74_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_75_NAME,
        STAI_NETWORK_WEIGHTS_75_FLAGS,
        STAI_NETWORK_WEIGHTS_75_FORMAT,
        STAI_NETWORK_WEIGHTS_75_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_75_RANK, STAI_NETWORK_WEIGHTS_75_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_76_NAME,
        STAI_NETWORK_WEIGHTS_76_FLAGS,
        STAI_NETWORK_WEIGHTS_76_FORMAT,
        STAI_NETWORK_WEIGHTS_76_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_76_RANK, STAI_NETWORK_WEIGHTS_76_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_77_NAME,
        STAI_NETWORK_WEIGHTS_77_FLAGS,
        STAI_NETWORK_WEIGHTS_77_FORMAT,
        STAI_NETWORK_WEIGHTS_77_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_77_RANK, STAI_NETWORK_WEIGHTS_77_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_78_NAME,
        STAI_NETWORK_WEIGHTS_78_FLAGS,
        STAI_NETWORK_WEIGHTS_78_FORMAT,
        STAI_NETWORK_WEIGHTS_78_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_78_RANK, STAI_NETWORK_WEIGHTS_78_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_79_NAME,
        STAI_NETWORK_WEIGHTS_79_FLAGS,
        STAI_NETWORK_WEIGHTS_79_FORMAT,
        STAI_NETWORK_WEIGHTS_79_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_79_RANK, STAI_NETWORK_WEIGHTS_79_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_80_NAME,
        STAI_NETWORK_WEIGHTS_80_FLAGS,
        STAI_NETWORK_WEIGHTS_80_FORMAT,
        STAI_NETWORK_WEIGHTS_80_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_80_RANK, STAI_NETWORK_WEIGHTS_80_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_81_NAME,
        STAI_NETWORK_WEIGHTS_81_FLAGS,
        STAI_NETWORK_WEIGHTS_81_FORMAT,
        STAI_NETWORK_WEIGHTS_81_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_81_RANK, STAI_NETWORK_WEIGHTS_81_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_82_NAME,
        STAI_NETWORK_WEIGHTS_82_FLAGS,
        STAI_NETWORK_WEIGHTS_82_FORMAT,
        STAI_NETWORK_WEIGHTS_82_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_82_RANK, STAI_NETWORK_WEIGHTS_82_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_83_NAME,
        STAI_NETWORK_WEIGHTS_83_FLAGS,
        STAI_NETWORK_WEIGHTS_83_FORMAT,
        STAI_NETWORK_WEIGHTS_83_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_83_RANK, STAI_NETWORK_WEIGHTS_83_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_84_NAME,
        STAI_NETWORK_WEIGHTS_84_FLAGS,
        STAI_NETWORK_WEIGHTS_84_FORMAT,
        STAI_NETWORK_WEIGHTS_84_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_84_RANK, STAI_NETWORK_WEIGHTS_84_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_85_NAME,
        STAI_NETWORK_WEIGHTS_85_FLAGS,
        STAI_NETWORK_WEIGHTS_85_FORMAT,
        STAI_NETWORK_WEIGHTS_85_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_85_RANK, STAI_NETWORK_WEIGHTS_85_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_86_NAME,
        STAI_NETWORK_WEIGHTS_86_FLAGS,
        STAI_NETWORK_WEIGHTS_86_FORMAT,
        STAI_NETWORK_WEIGHTS_86_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_86_RANK, STAI_NETWORK_WEIGHTS_86_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_87_NAME,
        STAI_NETWORK_WEIGHTS_87_FLAGS,
        STAI_NETWORK_WEIGHTS_87_FORMAT,
        STAI_NETWORK_WEIGHTS_87_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_87_RANK, STAI_NETWORK_WEIGHTS_87_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_88_NAME,
        STAI_NETWORK_WEIGHTS_88_FLAGS,
        STAI_NETWORK_WEIGHTS_88_FORMAT,
        STAI_NETWORK_WEIGHTS_88_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_88_RANK, STAI_NETWORK_WEIGHTS_88_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_89_NAME,
        STAI_NETWORK_WEIGHTS_89_FLAGS,
        STAI_NETWORK_WEIGHTS_89_FORMAT,
        STAI_NETWORK_WEIGHTS_89_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_89_RANK, STAI_NETWORK_WEIGHTS_89_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_90_NAME,
        STAI_NETWORK_WEIGHTS_90_FLAGS,
        STAI_NETWORK_WEIGHTS_90_FORMAT,
        STAI_NETWORK_WEIGHTS_90_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_90_RANK, STAI_NETWORK_WEIGHTS_90_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_91_NAME,
        STAI_NETWORK_WEIGHTS_91_FLAGS,
        STAI_NETWORK_WEIGHTS_91_FORMAT,
        STAI_NETWORK_WEIGHTS_91_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_91_RANK, STAI_NETWORK_WEIGHTS_91_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_92_NAME,
        STAI_NETWORK_WEIGHTS_92_FLAGS,
        STAI_NETWORK_WEIGHTS_92_FORMAT,
        STAI_NETWORK_WEIGHTS_92_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_92_RANK, STAI_NETWORK_WEIGHTS_92_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_93_NAME,
        STAI_NETWORK_WEIGHTS_93_FLAGS,
        STAI_NETWORK_WEIGHTS_93_FORMAT,
        STAI_NETWORK_WEIGHTS_93_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_93_RANK, STAI_NETWORK_WEIGHTS_93_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_94_NAME,
        STAI_NETWORK_WEIGHTS_94_FLAGS,
        STAI_NETWORK_WEIGHTS_94_FORMAT,
        STAI_NETWORK_WEIGHTS_94_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_94_RANK, STAI_NETWORK_WEIGHTS_94_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_95_NAME,
        STAI_NETWORK_WEIGHTS_95_FLAGS,
        STAI_NETWORK_WEIGHTS_95_FORMAT,
        STAI_NETWORK_WEIGHTS_95_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_95_RANK, STAI_NETWORK_WEIGHTS_95_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_96_NAME,
        STAI_NETWORK_WEIGHTS_96_FLAGS,
        STAI_NETWORK_WEIGHTS_96_FORMAT,
        STAI_NETWORK_WEIGHTS_96_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_96_RANK, STAI_NETWORK_WEIGHTS_96_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_97_NAME,
        STAI_NETWORK_WEIGHTS_97_FLAGS,
        STAI_NETWORK_WEIGHTS_97_FORMAT,
        STAI_NETWORK_WEIGHTS_97_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_97_RANK, STAI_NETWORK_WEIGHTS_97_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_98_NAME,
        STAI_NETWORK_WEIGHTS_98_FLAGS,
        STAI_NETWORK_WEIGHTS_98_FORMAT,
        STAI_NETWORK_WEIGHTS_98_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_98_RANK, STAI_NETWORK_WEIGHTS_98_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_99_NAME,
        STAI_NETWORK_WEIGHTS_99_FLAGS,
        STAI_NETWORK_WEIGHTS_99_FORMAT,
        STAI_NETWORK_WEIGHTS_99_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_99_RANK, STAI_NETWORK_WEIGHTS_99_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_100_NAME,
        STAI_NETWORK_WEIGHTS_100_FLAGS,
        STAI_NETWORK_WEIGHTS_100_FORMAT,
        STAI_NETWORK_WEIGHTS_100_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_100_RANK, STAI_NETWORK_WEIGHTS_100_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_101_NAME,
        STAI_NETWORK_WEIGHTS_101_FLAGS,
        STAI_NETWORK_WEIGHTS_101_FORMAT,
        STAI_NETWORK_WEIGHTS_101_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_101_RANK, STAI_NETWORK_WEIGHTS_101_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_102_NAME,
        STAI_NETWORK_WEIGHTS_102_FLAGS,
        STAI_NETWORK_WEIGHTS_102_FORMAT,
        STAI_NETWORK_WEIGHTS_102_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_102_RANK, STAI_NETWORK_WEIGHTS_102_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_103_NAME,
        STAI_NETWORK_WEIGHTS_103_FLAGS,
        STAI_NETWORK_WEIGHTS_103_FORMAT,
        STAI_NETWORK_WEIGHTS_103_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_103_RANK, STAI_NETWORK_WEIGHTS_103_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_104_NAME,
        STAI_NETWORK_WEIGHTS_104_FLAGS,
        STAI_NETWORK_WEIGHTS_104_FORMAT,
        STAI_NETWORK_WEIGHTS_104_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_104_RANK, STAI_NETWORK_WEIGHTS_104_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_105_NAME,
        STAI_NETWORK_WEIGHTS_105_FLAGS,
        STAI_NETWORK_WEIGHTS_105_FORMAT,
        STAI_NETWORK_WEIGHTS_105_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_105_RANK, STAI_NETWORK_WEIGHTS_105_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_106_NAME,
        STAI_NETWORK_WEIGHTS_106_FLAGS,
        STAI_NETWORK_WEIGHTS_106_FORMAT,
        STAI_NETWORK_WEIGHTS_106_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_106_RANK, STAI_NETWORK_WEIGHTS_106_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_107_NAME,
        STAI_NETWORK_WEIGHTS_107_FLAGS,
        STAI_NETWORK_WEIGHTS_107_FORMAT,
        STAI_NETWORK_WEIGHTS_107_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_107_RANK, STAI_NETWORK_WEIGHTS_107_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_108_NAME,
        STAI_NETWORK_WEIGHTS_108_FLAGS,
        STAI_NETWORK_WEIGHTS_108_FORMAT,
        STAI_NETWORK_WEIGHTS_108_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_108_RANK, STAI_NETWORK_WEIGHTS_108_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_109_NAME,
        STAI_NETWORK_WEIGHTS_109_FLAGS,
        STAI_NETWORK_WEIGHTS_109_FORMAT,
        STAI_NETWORK_WEIGHTS_109_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_109_RANK, STAI_NETWORK_WEIGHTS_109_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_110_NAME,
        STAI_NETWORK_WEIGHTS_110_FLAGS,
        STAI_NETWORK_WEIGHTS_110_FORMAT,
        STAI_NETWORK_WEIGHTS_110_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_110_RANK, STAI_NETWORK_WEIGHTS_110_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_111_NAME,
        STAI_NETWORK_WEIGHTS_111_FLAGS,
        STAI_NETWORK_WEIGHTS_111_FORMAT,
        STAI_NETWORK_WEIGHTS_111_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_111_RANK, STAI_NETWORK_WEIGHTS_111_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_112_NAME,
        STAI_NETWORK_WEIGHTS_112_FLAGS,
        STAI_NETWORK_WEIGHTS_112_FORMAT,
        STAI_NETWORK_WEIGHTS_112_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_112_RANK, STAI_NETWORK_WEIGHTS_112_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_113_NAME,
        STAI_NETWORK_WEIGHTS_113_FLAGS,
        STAI_NETWORK_WEIGHTS_113_FORMAT,
        STAI_NETWORK_WEIGHTS_113_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_113_RANK, STAI_NETWORK_WEIGHTS_113_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_114_NAME,
        STAI_NETWORK_WEIGHTS_114_FLAGS,
        STAI_NETWORK_WEIGHTS_114_FORMAT,
        STAI_NETWORK_WEIGHTS_114_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_114_RANK, STAI_NETWORK_WEIGHTS_114_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_115_NAME,
        STAI_NETWORK_WEIGHTS_115_FLAGS,
        STAI_NETWORK_WEIGHTS_115_FORMAT,
        STAI_NETWORK_WEIGHTS_115_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_115_RANK, STAI_NETWORK_WEIGHTS_115_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_116_NAME,
        STAI_NETWORK_WEIGHTS_116_FLAGS,
        STAI_NETWORK_WEIGHTS_116_FORMAT,
        STAI_NETWORK_WEIGHTS_116_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_116_RANK, STAI_NETWORK_WEIGHTS_116_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_117_NAME,
        STAI_NETWORK_WEIGHTS_117_FLAGS,
        STAI_NETWORK_WEIGHTS_117_FORMAT,
        STAI_NETWORK_WEIGHTS_117_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_117_RANK, STAI_NETWORK_WEIGHTS_117_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_118_NAME,
        STAI_NETWORK_WEIGHTS_118_FLAGS,
        STAI_NETWORK_WEIGHTS_118_FORMAT,
        STAI_NETWORK_WEIGHTS_118_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_118_RANK, STAI_NETWORK_WEIGHTS_118_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_119_NAME,
        STAI_NETWORK_WEIGHTS_119_FLAGS,
        STAI_NETWORK_WEIGHTS_119_FORMAT,
        STAI_NETWORK_WEIGHTS_119_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_119_RANK, STAI_NETWORK_WEIGHTS_119_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_120_NAME,
        STAI_NETWORK_WEIGHTS_120_FLAGS,
        STAI_NETWORK_WEIGHTS_120_FORMAT,
        STAI_NETWORK_WEIGHTS_120_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_120_RANK, STAI_NETWORK_WEIGHTS_120_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_121_NAME,
        STAI_NETWORK_WEIGHTS_121_FLAGS,
        STAI_NETWORK_WEIGHTS_121_FORMAT,
        STAI_NETWORK_WEIGHTS_121_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_121_RANK, STAI_NETWORK_WEIGHTS_121_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_122_NAME,
        STAI_NETWORK_WEIGHTS_122_FLAGS,
        STAI_NETWORK_WEIGHTS_122_FORMAT,
        STAI_NETWORK_WEIGHTS_122_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_122_RANK, STAI_NETWORK_WEIGHTS_122_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_123_NAME,
        STAI_NETWORK_WEIGHTS_123_FLAGS,
        STAI_NETWORK_WEIGHTS_123_FORMAT,
        STAI_NETWORK_WEIGHTS_123_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_123_RANK, STAI_NETWORK_WEIGHTS_123_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_124_NAME,
        STAI_NETWORK_WEIGHTS_124_FLAGS,
        STAI_NETWORK_WEIGHTS_124_FORMAT,
        STAI_NETWORK_WEIGHTS_124_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_124_RANK, STAI_NETWORK_WEIGHTS_124_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_125_NAME,
        STAI_NETWORK_WEIGHTS_125_FLAGS,
        STAI_NETWORK_WEIGHTS_125_FORMAT,
        STAI_NETWORK_WEIGHTS_125_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_125_RANK, STAI_NETWORK_WEIGHTS_125_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_126_NAME,
        STAI_NETWORK_WEIGHTS_126_FLAGS,
        STAI_NETWORK_WEIGHTS_126_FORMAT,
        STAI_NETWORK_WEIGHTS_126_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_126_RANK, STAI_NETWORK_WEIGHTS_126_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_127_NAME,
        STAI_NETWORK_WEIGHTS_127_FLAGS,
        STAI_NETWORK_WEIGHTS_127_FORMAT,
        STAI_NETWORK_WEIGHTS_127_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_127_RANK, STAI_NETWORK_WEIGHTS_127_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_128_NAME,
        STAI_NETWORK_WEIGHTS_128_FLAGS,
        STAI_NETWORK_WEIGHTS_128_FORMAT,
        STAI_NETWORK_WEIGHTS_128_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_128_RANK, STAI_NETWORK_WEIGHTS_128_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_129_NAME,
        STAI_NETWORK_WEIGHTS_129_FLAGS,
        STAI_NETWORK_WEIGHTS_129_FORMAT,
        STAI_NETWORK_WEIGHTS_129_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_129_RANK, STAI_NETWORK_WEIGHTS_129_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_130_NAME,
        STAI_NETWORK_WEIGHTS_130_FLAGS,
        STAI_NETWORK_WEIGHTS_130_FORMAT,
        STAI_NETWORK_WEIGHTS_130_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_130_RANK, STAI_NETWORK_WEIGHTS_130_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_131_NAME,
        STAI_NETWORK_WEIGHTS_131_FLAGS,
        STAI_NETWORK_WEIGHTS_131_FORMAT,
        STAI_NETWORK_WEIGHTS_131_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_131_RANK, STAI_NETWORK_WEIGHTS_131_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_132_NAME,
        STAI_NETWORK_WEIGHTS_132_FLAGS,
        STAI_NETWORK_WEIGHTS_132_FORMAT,
        STAI_NETWORK_WEIGHTS_132_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_132_RANK, STAI_NETWORK_WEIGHTS_132_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_133_NAME,
        STAI_NETWORK_WEIGHTS_133_FLAGS,
        STAI_NETWORK_WEIGHTS_133_FORMAT,
        STAI_NETWORK_WEIGHTS_133_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_133_RANK, STAI_NETWORK_WEIGHTS_133_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_134_NAME,
        STAI_NETWORK_WEIGHTS_134_FLAGS,
        STAI_NETWORK_WEIGHTS_134_FORMAT,
        STAI_NETWORK_WEIGHTS_134_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_134_RANK, STAI_NETWORK_WEIGHTS_134_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_135_NAME,
        STAI_NETWORK_WEIGHTS_135_FLAGS,
        STAI_NETWORK_WEIGHTS_135_FORMAT,
        STAI_NETWORK_WEIGHTS_135_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_135_RANK, STAI_NETWORK_WEIGHTS_135_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_136_NAME,
        STAI_NETWORK_WEIGHTS_136_FLAGS,
        STAI_NETWORK_WEIGHTS_136_FORMAT,
        STAI_NETWORK_WEIGHTS_136_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_136_RANK, STAI_NETWORK_WEIGHTS_136_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_137_NAME,
        STAI_NETWORK_WEIGHTS_137_FLAGS,
        STAI_NETWORK_WEIGHTS_137_FORMAT,
        STAI_NETWORK_WEIGHTS_137_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_137_RANK, STAI_NETWORK_WEIGHTS_137_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_138_NAME,
        STAI_NETWORK_WEIGHTS_138_FLAGS,
        STAI_NETWORK_WEIGHTS_138_FORMAT,
        STAI_NETWORK_WEIGHTS_138_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_138_RANK, STAI_NETWORK_WEIGHTS_138_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_139_NAME,
        STAI_NETWORK_WEIGHTS_139_FLAGS,
        STAI_NETWORK_WEIGHTS_139_FORMAT,
        STAI_NETWORK_WEIGHTS_139_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_139_RANK, STAI_NETWORK_WEIGHTS_139_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_140_NAME,
        STAI_NETWORK_WEIGHTS_140_FLAGS,
        STAI_NETWORK_WEIGHTS_140_FORMAT,
        STAI_NETWORK_WEIGHTS_140_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_140_RANK, STAI_NETWORK_WEIGHTS_140_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_141_NAME,
        STAI_NETWORK_WEIGHTS_141_FLAGS,
        STAI_NETWORK_WEIGHTS_141_FORMAT,
        STAI_NETWORK_WEIGHTS_141_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_141_RANK, STAI_NETWORK_WEIGHTS_141_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_142_NAME,
        STAI_NETWORK_WEIGHTS_142_FLAGS,
        STAI_NETWORK_WEIGHTS_142_FORMAT,
        STAI_NETWORK_WEIGHTS_142_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_142_RANK, STAI_NETWORK_WEIGHTS_142_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_143_NAME,
        STAI_NETWORK_WEIGHTS_143_FLAGS,
        STAI_NETWORK_WEIGHTS_143_FORMAT,
        STAI_NETWORK_WEIGHTS_143_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_143_RANK, STAI_NETWORK_WEIGHTS_143_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_144_NAME,
        STAI_NETWORK_WEIGHTS_144_FLAGS,
        STAI_NETWORK_WEIGHTS_144_FORMAT,
        STAI_NETWORK_WEIGHTS_144_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_144_RANK, STAI_NETWORK_WEIGHTS_144_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_145_NAME,
        STAI_NETWORK_WEIGHTS_145_FLAGS,
        STAI_NETWORK_WEIGHTS_145_FORMAT,
        STAI_NETWORK_WEIGHTS_145_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_145_RANK, STAI_NETWORK_WEIGHTS_145_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_146_NAME,
        STAI_NETWORK_WEIGHTS_146_FLAGS,
        STAI_NETWORK_WEIGHTS_146_FORMAT,
        STAI_NETWORK_WEIGHTS_146_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_146_RANK, STAI_NETWORK_WEIGHTS_146_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_147_NAME,
        STAI_NETWORK_WEIGHTS_147_FLAGS,
        STAI_NETWORK_WEIGHTS_147_FORMAT,
        STAI_NETWORK_WEIGHTS_147_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_147_RANK, STAI_NETWORK_WEIGHTS_147_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_148_NAME,
        STAI_NETWORK_WEIGHTS_148_FLAGS,
        STAI_NETWORK_WEIGHTS_148_FORMAT,
        STAI_NETWORK_WEIGHTS_148_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_148_RANK, STAI_NETWORK_WEIGHTS_148_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_149_NAME,
        STAI_NETWORK_WEIGHTS_149_FLAGS,
        STAI_NETWORK_WEIGHTS_149_FORMAT,
        STAI_NETWORK_WEIGHTS_149_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_149_RANK, STAI_NETWORK_WEIGHTS_149_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_150_NAME,
        STAI_NETWORK_WEIGHTS_150_FLAGS,
        STAI_NETWORK_WEIGHTS_150_FORMAT,
        STAI_NETWORK_WEIGHTS_150_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_150_RANK, STAI_NETWORK_WEIGHTS_150_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_151_NAME,
        STAI_NETWORK_WEIGHTS_151_FLAGS,
        STAI_NETWORK_WEIGHTS_151_FORMAT,
        STAI_NETWORK_WEIGHTS_151_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_151_RANK, STAI_NETWORK_WEIGHTS_151_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_152_NAME,
        STAI_NETWORK_WEIGHTS_152_FLAGS,
        STAI_NETWORK_WEIGHTS_152_FORMAT,
        STAI_NETWORK_WEIGHTS_152_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_152_RANK, STAI_NETWORK_WEIGHTS_152_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_153_NAME,
        STAI_NETWORK_WEIGHTS_153_FLAGS,
        STAI_NETWORK_WEIGHTS_153_FORMAT,
        STAI_NETWORK_WEIGHTS_153_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_153_RANK, STAI_NETWORK_WEIGHTS_153_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_154_NAME,
        STAI_NETWORK_WEIGHTS_154_FLAGS,
        STAI_NETWORK_WEIGHTS_154_FORMAT,
        STAI_NETWORK_WEIGHTS_154_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_154_RANK, STAI_NETWORK_WEIGHTS_154_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_155_NAME,
        STAI_NETWORK_WEIGHTS_155_FLAGS,
        STAI_NETWORK_WEIGHTS_155_FORMAT,
        STAI_NETWORK_WEIGHTS_155_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_155_RANK, STAI_NETWORK_WEIGHTS_155_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_156_NAME,
        STAI_NETWORK_WEIGHTS_156_FLAGS,
        STAI_NETWORK_WEIGHTS_156_FORMAT,
        STAI_NETWORK_WEIGHTS_156_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_156_RANK, STAI_NETWORK_WEIGHTS_156_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_157_NAME,
        STAI_NETWORK_WEIGHTS_157_FLAGS,
        STAI_NETWORK_WEIGHTS_157_FORMAT,
        STAI_NETWORK_WEIGHTS_157_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_157_RANK, STAI_NETWORK_WEIGHTS_157_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_158_NAME,
        STAI_NETWORK_WEIGHTS_158_FLAGS,
        STAI_NETWORK_WEIGHTS_158_FORMAT,
        STAI_NETWORK_WEIGHTS_158_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_158_RANK, STAI_NETWORK_WEIGHTS_158_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_159_NAME,
        STAI_NETWORK_WEIGHTS_159_FLAGS,
        STAI_NETWORK_WEIGHTS_159_FORMAT,
        STAI_NETWORK_WEIGHTS_159_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_159_RANK, STAI_NETWORK_WEIGHTS_159_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_160_NAME,
        STAI_NETWORK_WEIGHTS_160_FLAGS,
        STAI_NETWORK_WEIGHTS_160_FORMAT,
        STAI_NETWORK_WEIGHTS_160_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_160_RANK, STAI_NETWORK_WEIGHTS_160_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_161_NAME,
        STAI_NETWORK_WEIGHTS_161_FLAGS,
        STAI_NETWORK_WEIGHTS_161_FORMAT,
        STAI_NETWORK_WEIGHTS_161_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_161_RANK, STAI_NETWORK_WEIGHTS_161_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_162_NAME,
        STAI_NETWORK_WEIGHTS_162_FLAGS,
        STAI_NETWORK_WEIGHTS_162_FORMAT,
        STAI_NETWORK_WEIGHTS_162_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_162_RANK, STAI_NETWORK_WEIGHTS_162_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_163_NAME,
        STAI_NETWORK_WEIGHTS_163_FLAGS,
        STAI_NETWORK_WEIGHTS_163_FORMAT,
        STAI_NETWORK_WEIGHTS_163_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_163_RANK, STAI_NETWORK_WEIGHTS_163_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_164_NAME,
        STAI_NETWORK_WEIGHTS_164_FLAGS,
        STAI_NETWORK_WEIGHTS_164_FORMAT,
        STAI_NETWORK_WEIGHTS_164_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_164_RANK, STAI_NETWORK_WEIGHTS_164_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_165_NAME,
        STAI_NETWORK_WEIGHTS_165_FLAGS,
        STAI_NETWORK_WEIGHTS_165_FORMAT,
        STAI_NETWORK_WEIGHTS_165_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_165_RANK, STAI_NETWORK_WEIGHTS_165_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_166_NAME,
        STAI_NETWORK_WEIGHTS_166_FLAGS,
        STAI_NETWORK_WEIGHTS_166_FORMAT,
        STAI_NETWORK_WEIGHTS_166_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_166_RANK, STAI_NETWORK_WEIGHTS_166_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_167_NAME,
        STAI_NETWORK_WEIGHTS_167_FLAGS,
        STAI_NETWORK_WEIGHTS_167_FORMAT,
        STAI_NETWORK_WEIGHTS_167_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_167_RANK, STAI_NETWORK_WEIGHTS_167_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_168_NAME,
        STAI_NETWORK_WEIGHTS_168_FLAGS,
        STAI_NETWORK_WEIGHTS_168_FORMAT,
        STAI_NETWORK_WEIGHTS_168_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_168_RANK, STAI_NETWORK_WEIGHTS_168_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_169_NAME,
        STAI_NETWORK_WEIGHTS_169_FLAGS,
        STAI_NETWORK_WEIGHTS_169_FORMAT,
        STAI_NETWORK_WEIGHTS_169_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_169_RANK, STAI_NETWORK_WEIGHTS_169_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_170_NAME,
        STAI_NETWORK_WEIGHTS_170_FLAGS,
        STAI_NETWORK_WEIGHTS_170_FORMAT,
        STAI_NETWORK_WEIGHTS_170_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_170_RANK, STAI_NETWORK_WEIGHTS_170_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_171_NAME,
        STAI_NETWORK_WEIGHTS_171_FLAGS,
        STAI_NETWORK_WEIGHTS_171_FORMAT,
        STAI_NETWORK_WEIGHTS_171_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_171_RANK, STAI_NETWORK_WEIGHTS_171_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_172_NAME,
        STAI_NETWORK_WEIGHTS_172_FLAGS,
        STAI_NETWORK_WEIGHTS_172_FORMAT,
        STAI_NETWORK_WEIGHTS_172_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_172_RANK, STAI_NETWORK_WEIGHTS_172_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_173_NAME,
        STAI_NETWORK_WEIGHTS_173_FLAGS,
        STAI_NETWORK_WEIGHTS_173_FORMAT,
        STAI_NETWORK_WEIGHTS_173_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_173_RANK, STAI_NETWORK_WEIGHTS_173_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_174_NAME,
        STAI_NETWORK_WEIGHTS_174_FLAGS,
        STAI_NETWORK_WEIGHTS_174_FORMAT,
        STAI_NETWORK_WEIGHTS_174_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_174_RANK, STAI_NETWORK_WEIGHTS_174_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_175_NAME,
        STAI_NETWORK_WEIGHTS_175_FLAGS,
        STAI_NETWORK_WEIGHTS_175_FORMAT,
        STAI_NETWORK_WEIGHTS_175_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_175_RANK, STAI_NETWORK_WEIGHTS_175_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_176_NAME,
        STAI_NETWORK_WEIGHTS_176_FLAGS,
        STAI_NETWORK_WEIGHTS_176_FORMAT,
        STAI_NETWORK_WEIGHTS_176_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_176_RANK, STAI_NETWORK_WEIGHTS_176_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_177_NAME,
        STAI_NETWORK_WEIGHTS_177_FLAGS,
        STAI_NETWORK_WEIGHTS_177_FORMAT,
        STAI_NETWORK_WEIGHTS_177_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_177_RANK, STAI_NETWORK_WEIGHTS_177_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_178_NAME,
        STAI_NETWORK_WEIGHTS_178_FLAGS,
        STAI_NETWORK_WEIGHTS_178_FORMAT,
        STAI_NETWORK_WEIGHTS_178_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_178_RANK, STAI_NETWORK_WEIGHTS_178_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_179_NAME,
        STAI_NETWORK_WEIGHTS_179_FLAGS,
        STAI_NETWORK_WEIGHTS_179_FORMAT,
        STAI_NETWORK_WEIGHTS_179_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_179_RANK, STAI_NETWORK_WEIGHTS_179_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_180_NAME,
        STAI_NETWORK_WEIGHTS_180_FLAGS,
        STAI_NETWORK_WEIGHTS_180_FORMAT,
        STAI_NETWORK_WEIGHTS_180_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_180_RANK, STAI_NETWORK_WEIGHTS_180_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_181_NAME,
        STAI_NETWORK_WEIGHTS_181_FLAGS,
        STAI_NETWORK_WEIGHTS_181_FORMAT,
        STAI_NETWORK_WEIGHTS_181_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_181_RANK, STAI_NETWORK_WEIGHTS_181_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_182_NAME,
        STAI_NETWORK_WEIGHTS_182_FLAGS,
        STAI_NETWORK_WEIGHTS_182_FORMAT,
        STAI_NETWORK_WEIGHTS_182_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_182_RANK, STAI_NETWORK_WEIGHTS_182_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_183_NAME,
        STAI_NETWORK_WEIGHTS_183_FLAGS,
        STAI_NETWORK_WEIGHTS_183_FORMAT,
        STAI_NETWORK_WEIGHTS_183_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_183_RANK, STAI_NETWORK_WEIGHTS_183_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_184_NAME,
        STAI_NETWORK_WEIGHTS_184_FLAGS,
        STAI_NETWORK_WEIGHTS_184_FORMAT,
        STAI_NETWORK_WEIGHTS_184_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_184_RANK, STAI_NETWORK_WEIGHTS_184_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_185_NAME,
        STAI_NETWORK_WEIGHTS_185_FLAGS,
        STAI_NETWORK_WEIGHTS_185_FORMAT,
        STAI_NETWORK_WEIGHTS_185_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_185_RANK, STAI_NETWORK_WEIGHTS_185_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_186_NAME,
        STAI_NETWORK_WEIGHTS_186_FLAGS,
        STAI_NETWORK_WEIGHTS_186_FORMAT,
        STAI_NETWORK_WEIGHTS_186_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_186_RANK, STAI_NETWORK_WEIGHTS_186_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_187_NAME,
        STAI_NETWORK_WEIGHTS_187_FLAGS,
        STAI_NETWORK_WEIGHTS_187_FORMAT,
        STAI_NETWORK_WEIGHTS_187_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_187_RANK, STAI_NETWORK_WEIGHTS_187_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_188_NAME,
        STAI_NETWORK_WEIGHTS_188_FLAGS,
        STAI_NETWORK_WEIGHTS_188_FORMAT,
        STAI_NETWORK_WEIGHTS_188_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_188_RANK, STAI_NETWORK_WEIGHTS_188_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_189_NAME,
        STAI_NETWORK_WEIGHTS_189_FLAGS,
        STAI_NETWORK_WEIGHTS_189_FORMAT,
        STAI_NETWORK_WEIGHTS_189_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_189_RANK, STAI_NETWORK_WEIGHTS_189_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_190_NAME,
        STAI_NETWORK_WEIGHTS_190_FLAGS,
        STAI_NETWORK_WEIGHTS_190_FORMAT,
        STAI_NETWORK_WEIGHTS_190_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_190_RANK, STAI_NETWORK_WEIGHTS_190_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_191_NAME,
        STAI_NETWORK_WEIGHTS_191_FLAGS,
        STAI_NETWORK_WEIGHTS_191_FORMAT,
        STAI_NETWORK_WEIGHTS_191_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_191_RANK, STAI_NETWORK_WEIGHTS_191_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_192_NAME,
        STAI_NETWORK_WEIGHTS_192_FLAGS,
        STAI_NETWORK_WEIGHTS_192_FORMAT,
        STAI_NETWORK_WEIGHTS_192_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_192_RANK, STAI_NETWORK_WEIGHTS_192_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_193_NAME,
        STAI_NETWORK_WEIGHTS_193_FLAGS,
        STAI_NETWORK_WEIGHTS_193_FORMAT,
        STAI_NETWORK_WEIGHTS_193_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_193_RANK, STAI_NETWORK_WEIGHTS_193_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_194_NAME,
        STAI_NETWORK_WEIGHTS_194_FLAGS,
        STAI_NETWORK_WEIGHTS_194_FORMAT,
        STAI_NETWORK_WEIGHTS_194_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_194_RANK, STAI_NETWORK_WEIGHTS_194_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_195_NAME,
        STAI_NETWORK_WEIGHTS_195_FLAGS,
        STAI_NETWORK_WEIGHTS_195_FORMAT,
        STAI_NETWORK_WEIGHTS_195_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_195_RANK, STAI_NETWORK_WEIGHTS_195_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_196_NAME,
        STAI_NETWORK_WEIGHTS_196_FLAGS,
        STAI_NETWORK_WEIGHTS_196_FORMAT,
        STAI_NETWORK_WEIGHTS_196_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_196_RANK, STAI_NETWORK_WEIGHTS_196_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_197_NAME,
        STAI_NETWORK_WEIGHTS_197_FLAGS,
        STAI_NETWORK_WEIGHTS_197_FORMAT,
        STAI_NETWORK_WEIGHTS_197_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_197_RANK, STAI_NETWORK_WEIGHTS_197_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_198_NAME,
        STAI_NETWORK_WEIGHTS_198_FLAGS,
        STAI_NETWORK_WEIGHTS_198_FORMAT,
        STAI_NETWORK_WEIGHTS_198_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_198_RANK, STAI_NETWORK_WEIGHTS_198_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_199_NAME,
        STAI_NETWORK_WEIGHTS_199_FLAGS,
        STAI_NETWORK_WEIGHTS_199_FORMAT,
        STAI_NETWORK_WEIGHTS_199_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_199_RANK, STAI_NETWORK_WEIGHTS_199_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_200_NAME,
        STAI_NETWORK_WEIGHTS_200_FLAGS,
        STAI_NETWORK_WEIGHTS_200_FORMAT,
        STAI_NETWORK_WEIGHTS_200_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_200_RANK, STAI_NETWORK_WEIGHTS_200_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_201_NAME,
        STAI_NETWORK_WEIGHTS_201_FLAGS,
        STAI_NETWORK_WEIGHTS_201_FORMAT,
        STAI_NETWORK_WEIGHTS_201_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_201_RANK, STAI_NETWORK_WEIGHTS_201_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_202_NAME,
        STAI_NETWORK_WEIGHTS_202_FLAGS,
        STAI_NETWORK_WEIGHTS_202_FORMAT,
        STAI_NETWORK_WEIGHTS_202_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_202_RANK, STAI_NETWORK_WEIGHTS_202_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_203_NAME,
        STAI_NETWORK_WEIGHTS_203_FLAGS,
        STAI_NETWORK_WEIGHTS_203_FORMAT,
        STAI_NETWORK_WEIGHTS_203_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_203_RANK, STAI_NETWORK_WEIGHTS_203_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_204_NAME,
        STAI_NETWORK_WEIGHTS_204_FLAGS,
        STAI_NETWORK_WEIGHTS_204_FORMAT,
        STAI_NETWORK_WEIGHTS_204_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_204_RANK, STAI_NETWORK_WEIGHTS_204_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_205_NAME,
        STAI_NETWORK_WEIGHTS_205_FLAGS,
        STAI_NETWORK_WEIGHTS_205_FORMAT,
        STAI_NETWORK_WEIGHTS_205_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_205_RANK, STAI_NETWORK_WEIGHTS_205_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_206_NAME,
        STAI_NETWORK_WEIGHTS_206_FLAGS,
        STAI_NETWORK_WEIGHTS_206_FORMAT,
        STAI_NETWORK_WEIGHTS_206_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_206_RANK, STAI_NETWORK_WEIGHTS_206_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
      STAI_INIT_TENSOR(
        STAI_NETWORK_WEIGHTS_207_NAME,
        STAI_NETWORK_WEIGHTS_207_FLAGS,
        STAI_NETWORK_WEIGHTS_207_FORMAT,
        STAI_NETWORK_WEIGHTS_207_SIZE_BYTES,
        STAI_DECLARE_ARRAY(int32_t, STAI_NETWORK_WEIGHTS_207_RANK, STAI_NETWORK_WEIGHTS_207_SHAPE),
        STAI_EMPTY_ARRAY(),
        STAI_EMPTY_ARRAY()
        ),
    },
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
};

