# User-maintained AI integration for STM32N6 Neural-ART runtime.
# This file is included from Appli/CMakeLists.txt and is not generated by CubeMX.

set(AI_APP_DIR ${CMAKE_CURRENT_SOURCE_DIR}/AI/App)
set(AI_GEN_DIR ${CMAKE_CURRENT_SOURCE_DIR}/AI/generated)
set(AI_POSE_GEN_DIR ${CMAKE_CURRENT_SOURCE_DIR}/AI/models/pose/generated)
set(AI_SEG_GEN_DIR ${CMAKE_CURRENT_SOURCE_DIR}/AI/models/seg/generated)
set(AI_MW_DIR ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/ST/AI)
set(AI_NPU_DIR ${AI_MW_DIR}/Npu)


set(AI_APP_SOURCES
    ${AI_APP_DIR}/app_x-cube-ai.c
    ${AI_APP_DIR}/npu_cache.c
    ${AI_APP_DIR}/npu_init.c
    ${AI_APP_DIR}/network_pose_wrap.c
    ${AI_APP_DIR}/network_seg_wrap.c
)

set(AI_RUNTIME_SOURCES
    ${AI_NPU_DIR}/ecloader.c
    ${AI_NPU_DIR}/ll_aton.c
    ${AI_NPU_DIR}/ll_aton_cipher.c
    ${AI_NPU_DIR}/ll_aton_dbgtrc.c
    ${AI_NPU_DIR}/ll_aton_debug.c
    ${AI_NPU_DIR}/ll_aton_lib.c
    ${AI_NPU_DIR}/ll_aton_lib_sw_operators.c
    ${AI_NPU_DIR}/ll_aton_profiler.c
    ${AI_NPU_DIR}/ll_aton_reloc_callbacks.c
    ${AI_NPU_DIR}/ll_aton_reloc_network.c
    ${AI_NPU_DIR}/ll_aton_rt_main.c
    ${AI_NPU_DIR}/ll_aton_runtime.c
    ${AI_NPU_DIR}/ll_aton_util.c
    ${AI_NPU_DIR}/ll_sw_float.c
    ${AI_NPU_DIR}/ll_sw_integer.c
    ${AI_NPU_DIR}/mcu_cache.c
)

file(GLOB THREADX_COMMON_SOURCES
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/ST/threadx/common/src/*.c
)
file(GLOB THREADX_PORT_C_SOURCES
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/ST/threadx/ports/cortex_m55/gnu/src/*.c
)
file(GLOB THREADX_PORT_ASM_SOURCES
    ${CMAKE_CURRENT_SOURCE_DIR}/../Middlewares/ST/threadx/ports/cortex_m55/gnu/src/*.S
)

set(THREADX_APP_SOURCES
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Src/app_threadx.c
    ${CMAKE_CURRENT_SOURCE_DIR}/Core/Src/tx_initialize_low_level.S
)

# Keep AI translation units size-optimized even in Debug to fit ROM budget.
set_source_files_properties(${AI_APP_SOURCES} ${AI_RUNTIME_SOURCES}
    PROPERTIES COMPILE_OPTIONS "-Os;-g0"
)

# Add HAL modules required by NPU/RIF/cache setup.
target_sources(STM32_Drivers PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}/../Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_rif.c
)

# Add AI sources to application target.
target_sources(${CMAKE_PROJECT_NAME} PRIVATE
    ${AI_APP_SOURCES}
    ${AI_RUNTIME_SOURCES}
    ${THREADX_COMMON_SOURCES}
    ${THREADX_PORT_C_SOURCES}
    ${THREADX_PORT_ASM_SOURCES}
    ${THREADX_APP_SOURCES}
)

# Add include paths used by AI runtime and generated network code.
target_include_directories(stm32cubemx INTERFACE
    ${AI_APP_DIR}
    ${AI_GEN_DIR}
    ${AI_POSE_GEN_DIR}
    ${AI_SEG_GEN_DIR}
    ${AI_MW_DIR}/Inc
    ${AI_NPU_DIR}
)

# Required runtime configuration for STM32N6 + ThreadX based LL_ATON integration.
target_compile_definitions(stm32cubemx INTERFACE
    LL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6
    LL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL
    LL_ATON_RT_MODE=LL_ATON_RT_ASYNC
    LL_ATON_SW_FALLBACK=1
    USE_NPU_CACHE=1
    USE_THREADX_AI_RUNTIME
)

# Link ST AI runtime library.
target_link_directories(${CMAKE_PROJECT_NAME} PRIVATE
    ${AI_MW_DIR}/Lib
)

target_link_libraries(${CMAKE_PROJECT_NAME}
    :NetworkRuntime1100_CM55_GCC.a
    m
)
